FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./
COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/knexfile.js ./
COPY --from=builder /app/migration ./migration
COPY --from=builder /app/seeder ./seeder

EXPOSE 3000

CMD ["node", "dist/main"]